spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/twitter_db
    username: postgres
    password: 131270
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.yaml
    drop-first: false
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate:
        format_sql: true
    show-sql: true
logging:
  level:
    org:
      springframework:
        security: debug